var fieldMeta={produkt:[1,'PRODUKT','Wybierz produkt z katalogu. Dobierzemy materiał i zakres personalizacji.'],klub:[2,'EKIPA','Podaj nazwę klubu, ekipy lub firmy zamawiającej odzież.'],osoba:[3,'KONTAKT','Podaj osobę, z którą ustalimy szczegóły zamówienia.'],email:[4,'EMAIL','Na ten adres odpowiemy z wyceną lub pytaniami o produkcję.'],telefon:[5,'TELEFON','Numer jest opcjonalny. Ułatwi nam omówienie szczegółów.'],ilosc:[6,'ILOŚĆ','Podaj liczbę sztuk.'],termin:[7,'TERMIN','Wskaż oczekiwany termin.'],opis:[8,'BRIEF','Opisz zamówienie i dodaj materiały.']};
function updateLeft(){}
function toggleProd(){document.getElementById('fExtra').classList.add('open');}
function showField(id){var meta=fieldMeta[id];if(!meta)return;var ghost=document.getElementById('leftGhost');ghost.textContent=meta[1];ghost.classList.remove('is-glitch');void ghost.offsetWidth;ghost.classList.add('is-glitch');document.getElementById('leftDesc').textContent=meta[2];document.getElementById('leftStepTxt').textContent='Krok '+meta[0]+' / 8';document.getElementById('leftStepBar').style.width=(meta[0]/8*100)+'%';}
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('.f-block').forEach(function(b,i){setTimeout(function(){b.classList.add('in');},100+i*70);});
 Object.keys(fieldMeta).forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('focus',function(){document.querySelectorAll('.f-block').forEach(function(b){b.classList.remove('focused');});var block=el.closest('.f-block');if(block)block.classList.add('focused');showField(id);});});
 var selected=new URLSearchParams(location.search).get('produkt'),select=document.getElementById('produkt');if(selected){var option=Array.from(select.options).find(function(o){return o.value===selected;});if(option){select.value=selected;select.classList.add('filled');}else{document.getElementById('opis').value='Zapytanie o produkcję: '+selected;}}
 toggleProd();document.addEventListener('keydown',function(e){if(e.key==='Escape'&&document.getElementById('successOverlay').classList.contains('show'))closePreparedMail();});
});
async function handleSubmit(e){e.preventDefault();if(!e.target.reportValidity())return;var button=document.getElementById('submitBtn'),data=new FormData(e.target),files=data.getAll('zalaczniki').filter(function(f){return f&&f.size});if(files.reduce(function(n,f){return n+f.size},0)>20*1024*1024){alert('Łączny rozmiar załączników nie może przekroczyć 20 MB.');return}button.disabled=true;button.textContent='WYSYŁANIE…';try{var response=await fetch('/api/contact',{method:'POST',body:data,headers:{Accept:'application/json'}}),result=await response.json();if(!response.ok)throw new Error(result.error||'Nie udało się wysłać briefu.');document.getElementById('successMessage').textContent='Dziękujemy. Brief trafił do naszego zespołu — wrócimy z odpowiedzią.';document.getElementById('successOverlay').classList.add('show');e.target.reset()}catch(err){document.getElementById('successMessage').textContent=err.message+' Spróbuj ponownie za chwilę lub napisz na kontakt@dangerwear.pl.';document.getElementById('successOverlay').classList.add('show')}finally{button.disabled=false;button.textContent='WYŚLIJ BRIEF';}}
function closePreparedMail(){document.getElementById('successOverlay').classList.remove('show');document.getElementById('submitBtn').focus();}
