var fieldMeta={produkt:[1,'PRODUKT','Wybierz produkt z katalogu. Dobierzemy materiał i zakres personalizacji.'],klub:[2,'EKIPA','Podaj nazwę klubu, ekipy lub firmy zamawiającej odzież.'],osoba:[3,'KONTAKT','Podaj osobę, z którą ustalimy szczegóły zamówienia.'],email:[4,'EMAIL','Na ten adres odpowiemy z wyceną lub pytaniami o produkcję.'],telefon:[5,'TELEFON','Numer jest opcjonalny. Ułatwi nam omówienie szczegółów.'],ilosc:[6,'ILOŚĆ','Podaj liczbę sztuk. Minimum produkcyjne ustalamy dla danego produktu.'],termin:[6,'TERMIN','Wskaż oczekiwany termin. Dostępność potwierdzimy przy wycenie.'],opis:[7,'PRODUKCJA','Opisz kolorystykę, nadruki, rozmiary i inne wymagania do produkcji.']};
function updateLeft(){}
function toggleProd(){document.getElementById('fExtra').classList.add('open');}
function showField(id){var meta=fieldMeta[id];if(!meta)return;document.getElementById('leftGhost').textContent=meta[1];document.getElementById('leftDesc').textContent=meta[2];document.getElementById('leftStepTxt').textContent='Krok '+meta[0]+' / 7';document.getElementById('leftStepBar').style.width=(meta[0]/7*100)+'%';}
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('.f-block').forEach(function(b,i){setTimeout(function(){b.classList.add('in');},100+i*70);});
 Object.keys(fieldMeta).forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('focus',function(){document.querySelectorAll('.f-block').forEach(function(b){b.classList.remove('focused');});var block=el.closest('.f-block');if(block)block.classList.add('focused');showField(id);});});
 var selected=new URLSearchParams(location.search).get('produkt'),select=document.getElementById('produkt');if(selected){var option=Array.from(select.options).find(function(o){return o.value===selected;});if(option){select.value=selected;select.classList.add('filled');}else{document.getElementById('opis').value='Zapytanie o produkcję: '+selected;}}
 toggleProd();document.addEventListener('keydown',function(e){if(e.key==='Escape'&&document.getElementById('successOverlay').classList.contains('show'))closePreparedMail();});
});
function handleSubmit(e){e.preventDefault();if(!e.target.reportValidity())return;var f=new FormData(e.target),rows=[['Produkt','produkt'],['Klub / Ekipa / Firma','klub'],['Osoba kontaktowa','osoba'],['Email','email'],['Telefon','telefon'],['Ilość sztuk','ilosc'],['Oczekiwany termin','termin'],['Opis zamówienia','opis']];var body='DANGER WEAR — ZAPYTANIE O PRODUKCJĘ\n\n'+rows.map(function(r){return r[0]+': '+(f.get(r[1])||'—');}).join('\n');var subject='[Danger Wear] Produkcja — '+f.get('produkt');var link=document.getElementById('openPreparedMail');link.href='mailto:k.patyk@dangerwear.pl?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);document.getElementById('successOverlay').classList.add('show');link.focus();}
function closePreparedMail(){document.getElementById('successOverlay').classList.remove('show');document.getElementById('submitBtn').focus();}
