'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>structuredClone(x), fields=['Materiał','Krój','Znakowanie','Personalizacja'];
let state,product=null,dirty=false,page='products',media=[],uploadRequest=null;
const slugify=s=>s.replace(/ł/g,'l').replace(/Ł/g,'L').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||'produkt';
const content=$('#content'),modal=$('#modal');
async function api(path,data){const r=await fetch(window.DW_BASE+'/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-DW-Token':window.DW_TOKEN}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok){if(result.login_required){toast('Sesja wygasła. Zaloguj się w nowej karcie i wróć tutaj — niezapisane wpisy pozostają w formularzu.',true);showSessionLogin()}const e=new Error(result.error||'Błąd połączenia.');e.details=result.errors;e.warnings=result.warnings;throw e}return result}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.className='show'+(error?' error':'');clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='',6000)}
function showError(e){toast(e.message,true);const target=$('#editorErrors');if(target){target.innerHTML=`<div class="notice error"><b>${esc(e.message)}</b>${(e.details||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}</div>`;target.scrollIntoView({behavior:'smooth',block:'center'})}}
function guard(fn){return async(...args)=>{try{await fn(...args)}catch(e){showError(e)}}}
function showModal(title,markup){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=markup;if(!modal.open)modal.showModal()}
$('#closeModal').onclick=()=>{if(uploadRequest){uploadRequest.abort();uploadRequest=null}modal.close()};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
function markDirty(){dirty=true;const e=$('#saveStatus');if(e)e.textContent='Niezapisane zmiany';}
async function reload(){state=await api('state');$('#productCount').textContent=state.products.length}
function canLeave(){return !dirty||confirm('Masz niezapisane zmiany. Opuścić edycję i je odrzucić?')}
async function navigate(target){if(!canLeave())return;dirty=false;product=null;page=target;$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===target));const titles={clubs:'Kluby',methodPhotos:'Zdjęcia metod znakowania',products:'Produkty',media:'Biblioteka zdjęć',methods:'Metody znakowania',tables:'Tabele rozmiarów',categories:'Kategorie',history:'Publikacje i historia',backup:'Kopie zapasowe',social:'DW Social Media'};$('#pageTitle').textContent=titles[target];$('#newProduct').hidden=target!=='products';await reload();if(target==='clubs')await renderClubs();if(target==='methodPhotos')await renderMethodPhotos();if(target==='products')renderProducts();if(target==='media')await renderLibrary();if(['methods','categories','tables'].includes(target))renderCatalog(target);if(target==='history')await historyPage();if(target==='backup')renderBackup();if(target==='social')content.innerHTML=`<iframe title="DW Social Media" src="${window.DW_BASE}/social" style="width:100%;min-height:calc(100vh - 160px);border:0;border-radius:10px;background:#101116"></iframe>`}
$$('.nav').forEach(n=>n.onclick=guard(()=>navigate(n.dataset.page)));
$('#newProduct').onclick=guard(async()=>{if(!canLeave())return;const r=await api('create',{});dirty=false;await reload();openEditor(r.product.id)});
function renderProducts(){
 const changed=state.products.filter(p=>p.published_revision!==p.revision).length;
 content.innerHTML=`<div class="intro"><p>Twoja oferta, pod kontrolą.<br>Edytuj treść, zdjęcia i rozmiary. Zmiany zastosujesz dopiero po sprawdzeniu podglądu.</p><div class="stats"><div><strong>${state.products.length}</strong><small>produktów</small></div><div><strong>${changed}</strong><small>wersji roboczych</small></div><div><strong>${state.catalog.categories.length}</strong><small>kategorie oferty</small></div></div></div><div class="toolbar"><input id="search" placeholder="Szukaj produktu…" aria-label="Szukaj produktu"><select id="categoryFilter" aria-label="Filtr kategorii"><option value="">Wszystkie kategorie</option>${state.catalog.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select><select id="statusFilter" aria-label="Filtr statusu"><option value="">Wszystkie statusy</option><option value="draft">Robocze zmiany</option><option value="ready">Zastosowane lokalnie</option></select></div><div id="cards" class="products-grid"></div>`;
 function cards(){const q=$('#search').value.toLocaleLowerCase('pl'),c=$('#categoryFilter').value,s=$('#statusFilter').value;const filtered=state.products.filter(p=>(p.name+' '+p.url).toLocaleLowerCase('pl').includes(q)&&(!c||p.category===c)&&(!s||(s==='draft')===(p.revision!==p.published_revision)));$('#cards').innerHTML=filtered.length?filtered.map(p=>{const photo=p.galleries.lifestyle[0],draft=p.revision!==p.published_revision,cat=state.catalog.categories.find(c=>c.id===p.category);return `<article class="product-card" tabindex="0" role="button" aria-label="Edytuj ${esc(p.name)}" data-id="${p.id}"><div class="card-image">${photo?`<img loading="lazy" src="${window.DW_BASE}/asset/${esc(photo.src)}" alt="${esc(photo.alt||p.name)}">`:''}<span class="status ${draft?'draft':''}">${draft?'● Szkic / zmiany':'● Strona lokalna'}</span></div><div class="card-copy"><span class="category">${esc(cat?.name||p.category)}</span>${p.errors?.length?'<span class="needs-review">Do uzupełnienia</span>':''}<h3>${esc(p.name)}</h3><div class="card-footer"><span>${p.galleries.lifestyle.length}/5 lifestyle · ${p.galleries.realizacje.length}/18 realizacji</span><b>Edytuj ↗</b></div></div></article>`}).join(''):'<div class="empty">Nie znaleziono produktów.</div>';$$('.product-card').forEach(e=>{e.onclick=()=>openEditor(e.dataset.id);e.onkeydown=k=>{if(k.key==='Enter'||k.key===' '){k.preventDefault();openEditor(e.dataset.id)}}})}
 $('#search').oninput=cards;$('#categoryFilter').onchange=cards;$('#statusFilter').onchange=cards;cards();
}
function openEditor(id){product=clone(state.products.find(p=>p.id===id));dirty=false;page='editor';$('#pageTitle').textContent='Edycja produktu';$('#newProduct').hidden=true;renderEditor();window.scrollTo(0,0)}
function field(label,id,value,type='text'){return `<label>${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}"></label>`}
function section(n,title,body,extra=''){return `<section class="section" id="section${n}"><div class="section-title"><h3><span class="number">${n}</span>${title}</h3>${extra}</div>${body}</section>`}
function renderEditor(){
 const p=product;p.parameters??=Object.entries(p.original_specs||p.specs||{}).map(([name,value])=>({name,value}));const cats=state.catalog.categories.map(c=>`<option value="${esc(c.id)}" ${p.category===c.id?'selected':''}>${esc(c.name)}${c.active?'':' (archiwalna)'}</option>`).join('');
 const methods=[...state.catalog.methods];p.methods.forEach(m=>{if(!methods.some(x=>x.id===m.id))methods.push(m)});
 content.innerHTML=`<button class="back" id="back">← Wszystkie produkty</button><div class="editor-head"><div><h2>${esc(p.name)}</h2><p><code>${esc(p.url)}</code> · Szkic v${p.revision}${p.published_revision?' · Na stronie v'+p.published_revision:''}</p></div><div class="editor-actions"><button id="duplicate">Duplikuj</button><button id="history">Historia</button>${state.folder_mode?'<button id="reloadFolder">Wczytaj kartę z folderu</button>':''}<button id="previewTop">Podgląd ↗</button></div></div><div class="workflow"><div><span class="workflow-num">1</span><b>Uzupełnij produkt</b><small>Dane i zdjęcia w jednym miejscu</small></div><div><span class="workflow-num">2</span><b>Sprawdź podgląd</b><small>Tak będzie wyglądała karta</small></div><div><span class="workflow-num">3</span><b>Zapisz do folderu strony</b><small>Zapis do folderu strony z kopią bezpieczeństwa</small></div></div><div id="editorErrors"></div>${p.notes?.length?`<div class="notice">${p.notes.map(esc).join('<br>')} Zachowano wartości źródłowe; sprawdź pola przed pierwszym zastosowaniem.</div>`:''}<div class="editor-layout"><nav class="section-nav" aria-label="Sekcje produktu">${['Kategoria','Nazwa i opis','Parametry','Tabela rozmiarów','Metody znakowania','Lifestyle','Realizacje'].map((s,i)=>`<a href="#section${i+1}"><span>0${i+1}</span>${s}</a>`).join('')}</nav><div>
 ${section(1,'Kategoria',`<label>Kategoria główna<select id="category">${cats}</select></label><p class="hint">Przy zastosowaniu zmiany program zaktualizuje nawigację i listing kategorii w folderze strony.</p>`)}
 ${section(2,'Nazwa i opis',`<div class="fields"><label class="full">Nazwa produktu<input id="name" maxlength="120" value="${esc(p.name)}"></label><label class="full">Adres strony<input id="slug" value="${esc(p.slug)}" ${p.imported||p.published_revision?'readonly':''}><small class="hint">${p.imported||p.published_revision?'Adres jest zachowany. Zmiana nazwy go nie zmienia.':'Możesz poprawić adres przed pierwszym zastosowaniem na stronie.'} Końcówka .html zostanie dodana automatycznie.</small></label><label class="full">Opis produktu<textarea id="description" rows="5" maxlength="3000">${esc(p.description)}</textarea></label></div>`)}
 ${section(3,'Parametry produktu',`<p class="hint">Ty wybierasz nazwy i wartości. Dodawaj dowolne wiersze, np. „Gramatura” → „180 g/m²” albo „Minimalne zamówienie” → „30 sztuk”.</p><div id="parametersEditor"></div>`)}
 ${section(4,'Tabela rozmiarów',`<label>Sposób dodania tabeli<select id="sizeMode"><option value="none" ${p.size.mode==='none'?'selected':''}>Brak tabeli</option><option value="template" ${p.size.mode==='template'?'selected':''}>Wybierz istniejący szablon</option><option value="custom" ${p.size.mode==='custom'?'selected':''}>Tabela indywidualna</option></select></label><div id="sizeEditor"></div>`)}
 ${section(5,'Metody znakowania',`<p class="hint">Wybierz metody dla tego produktu. Opisy i ikony dodasz w zakładce „Metody znakowania”. Zapis produktu utrwala wybraną wersję metody.</p><div class="method-select">${methods.filter(m=>m.active||p.methods.some(x=>x.id===m.id)).map(m=>`<label class="method-option">${m.icon?`<img class="method-icon" src="${window.DW_BASE}/asset/${esc(m.icon)}" alt="">`:''}<input type="checkbox" data-method="${esc(m.id)}" ${p.methods.some(x=>x.id===m.id)?'checked':''}>${esc(m.name)}<small>${esc(m.short||'')}${m.active?'':' · archiwalna'}</small></label>`).join('')}</div><button id="syncMarking" class="small" style="margin-top:15px">Ustaw parametr „Znakowanie” z wyboru</button>`)}
 ${section(6,'Galeria lifestyle',`<p class="hint">Pierwsze zdjęcie otwiera karuzelę. Dodaj podpis i ewentualny podtytuł.</p><label class="check"><input id="autoplay" type="checkbox" ${p.autoplay?'checked':''}>Automatyczna zmiana co 5 sekund</label><div id="lifestyleGallery"></div>`,`<span class="pill" id="lifestyleCount"></span>`)}
 ${section(7,'Galeria realizacji',`<p class="hint">Zdjęcia projektów są wyświetlane w całości w powiększeniu. Pusta galeria nie pojawia się na stronie.</p><div id="realizacjeGallery"></div>`,`<span class="pill" id="realizacjeCount"></span>`)}
 <div class="savebar"><small id="saveStatus">${dirty?'Niezapisane zmiany':'Szkic zapisany · v'+p.revision}</small><div><button id="save">Zapisz szkic</button><button id="preview">Podgląd</button><button id="publish" class="primary">Zastosuj na stronie</button></div></div></div></div>`;
 $('#back').onclick=guard(()=>navigate('products'));
 if($('#reloadFolder'))$('#reloadFolder').onclick=guard(async()=>{if(!confirm('Wczytać bieżący HTML jako nowy szkic? Zapisane wcześniejsze wersje pozostaną w historii; niezapisane wpisy zostaną zastąpione.'))return;const r=await api('reload-folder',{id:product.id,revision:product.revision});await reload();product=r.product;dirty=false;renderEditor();toast('Wczytano kartę z folderu jako nowy szkic.');});
 $('#duplicate').onclick=guard(async()=>{if(dirty)await save();const r=await api('create',{from:product.id});await reload();openEditor(r.product.id);toast('Utworzono kopię jako nowy szkic.')});
 $('#history').onclick=guard(()=>showHistory());$('#save').onclick=guard(()=>save());$('#preview').onclick=$('#previewTop').onclick=guard(()=>preview());$('#publish').onclick=guard(()=>publication());
 $('#name').oninput=e=>{p.name=e.target.value;if(!p.imported&&!p.published_revision&&!p.manualSlug){p.slug=slugify(p.name);p.url=p.slug+'.html';$('#slug').value=p.slug}markDirty()};$('#slug').oninput=e=>{p.manualSlug=true;p.slug=e.target.value;p.url=p.slug+'.html';markDirty()};$('#description').oninput=e=>{p.description=e.target.value;markDirty()};$('#category').onchange=e=>{p.category=e.target.value;markDirty()};$('#autoplay').onchange=e=>{p.autoplay=e.target.checked;markDirty()};
 $$('[data-method]').forEach(el=>el.onchange=()=>{p.methods=$$('[data-method]:checked').map(e=>clone(p.methods.find(m=>m.id===e.dataset.method)||state.catalog.methods.find(m=>m.id===e.dataset.method)));markDirty()});
 $('#syncMarking').onclick=()=>{p.methods=p.methods.map(m=>clone(state.catalog.methods.find(x=>x.id===m.id)||m));const value=p.methods.map(m=>m.short||m.name).join(', ');const row=p.parameters.find(r=>r.name.trim().toLocaleLowerCase('pl')==='znakowanie');if(row)row.value=value;else p.parameters.push({name:'Znakowanie',value});markDirty();renderParameters();toast('Parametr znakowania uzupełniony. Możesz zmienić jego nazwę i wartość.')};
 $('#sizeMode').onchange=e=>{p.size.mode=e.target.value;markDirty();renderSize()};renderParameters();renderSize();renderGallery('lifestyle');renderGallery('realizacje');
}
function renderParameters(){
 const rows=product.parameters,root=$('#parametersEditor');
 root.innerHTML=`<div class="parameter-heading"><span>Nazwa parametru</span><span>Wartość</span><span>Kolejność</span></div><div class="parameter-list">${rows.map((r,i)=>`<div class="parameter-row"><label><span class="mobile-label">Nazwa parametru</span><input data-param-name="${i}" aria-label="Nazwa parametru ${i+1}" value="${esc(r.name)}" placeholder="np. Materiał"></label><label><span class="mobile-label">Wartość</span><input data-param-value="${i}" aria-label="Wartość parametru ${i+1}" value="${esc(r.value)}" placeholder="np. 100% poliester"></label><div class="parameter-actions"><button type="button" data-param-up="${i}" ${i===0?'disabled':''} aria-label="Przesuń parametr ${i+1} w górę">↑</button><button type="button" data-param-down="${i}" ${i===rows.length-1?'disabled':''} aria-label="Przesuń parametr ${i+1} w dół">↓</button><button type="button" data-param-remove="${i}" class="danger" aria-label="Usuń parametr ${i+1}">×</button></div></div>`).join('')}</div>${rows.length?'':'<div class="empty compact">Brak parametrów. Dodaj pierwszy wiersz lub pozostaw sekcję pustą.</div>'}<button type="button" id="addParameter" class="outline-accent">＋ Dodaj parametr</button><p class="hint parameter-help">Nazwy, wartości, liczba i kolejność wierszy zależą od produktu. Nie musisz trzymać się czterech pól.</p>`;
 $$('[data-param-name]',root).forEach(e=>e.oninput=()=>{rows[+e.dataset.paramName].name=e.value;markDirty()});
 $$('[data-param-value]',root).forEach(e=>e.oninput=()=>{rows[+e.dataset.paramValue].value=e.value;markDirty()});
 $$('[data-param-remove]',root).forEach(e=>e.onclick=()=>{const i=+e.dataset.paramRemove;rows.splice(i,1);markDirty();renderParameters()});
 for(const [attr,delta] of [['paramUp',-1],['paramDown',1]])$$('[data-'+attr.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+']',root).forEach(e=>e.onclick=()=>{const i=+e.dataset[attr],j=i+delta;[rows[i],rows[j]]=[rows[j],rows[i]];markDirty();renderParameters()});
 $('#addParameter').onclick=()=>{rows.push({name:'',value:''});markDirty();renderParameters();$$('[data-param-name]',root).at(-1).focus()};
}
function renderSize(){
 const s=product.size,root=$('#sizeEditor');if(s.mode==='none'){root.innerHTML='<p class="hint">Sekcja tabeli będzie ukryta na karcie produktu.</p>';return}
 root.innerHTML=`${s.mode==='template'?`<label style="margin-top:14px">Szablon<select id="templateSelect"><option value="">Wybierz szablon…</option>${state.catalog.templates.map((t,i)=>`<option value="${i}">${esc(t.name)}</option>`).join('')}</select></label><p class="hint">Szablon jest kopiowany do produktu. Późniejsze zmiany szablonu nie zmienią tej tabeli.</p>`:''}<div class="table-scroll"><table class="size-table"><thead><tr><th>Pomiar</th>${s.columns.map((v,i)=>`<th><input aria-label="Nazwa rozmiaru ${i+1}" data-col="${i}" value="${esc(v)}"><button type="button" data-col-left="${i}" ${i===0?'disabled':''} aria-label="Rozmiar w lewo">←</button><button type="button" data-col-right="${i}" ${i===s.columns.length-1?'disabled':''} aria-label="Rozmiar w prawo">→</button><button type="button" data-del-col="${i}" class="danger" aria-label="Usuń rozmiar">×</button></th>`).join('')}</tr></thead><tbody>${s.rows.map((r,i)=>`<tr><th><input aria-label="Nazwa pomiaru ${i+1}" data-row="${i}" value="${esc(r.name)}"><button data-row-up="${i}" ${i===0?'disabled':''} aria-label="Pomiar w górę">↑</button><button data-row-down="${i}" ${i===s.rows.length-1?'disabled':''} aria-label="Pomiar w dół">↓</button><button data-del-row="${i}" class="danger" aria-label="Usuń pomiar">×</button></th>${r.values.map((v,j)=>`<td><input inputmode="decimal" aria-label="${esc(r.name)} ${esc(s.columns[j])}" data-cell="${i},${j}" value="${esc(v)}" placeholder="—"></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="gallery-buttons"><button id="addColumn" class="small">＋ Rozmiar</button><button id="addRow" class="small">＋ Pomiar</button><button id="saveTemplate" class="small">Zapisz jako szablon</button></div><p class="hint">Brak pomiaru oznacz „—”. Wartości mogą zawierać przecinek dziesiętny.</p><div class="fields">${field('Jednostka (do potwierdzenia)','unit',s.unit)}${field('Tolerancja (opcjonalnie)','tolerance',s.tolerance)}<label class="full">Sposób pomiaru<textarea id="instructions" rows="2">${esc(s.instructions)}</textarea></label></div>`;
 if($('#templateSelect'))$('#templateSelect').onchange=e=>{if(e.target.value==='')return;product.size=clone(state.catalog.templates[Number(e.target.value)].size);product.size.mode='template';markDirty();renderSize()};
 $$('[data-col]').forEach(e=>e.oninput=()=>{s.columns[+e.dataset.col]=e.value;markDirty()});$$('[data-row]').forEach(e=>e.oninput=()=>{s.rows[+e.dataset.row].name=e.value;markDirty()});$$('[data-cell]').forEach(e=>e.oninput=()=>{const [i,j]=e.dataset.cell.split(',').map(Number);s.rows[i].values[j]=e.value;markDirty()});
 for(const [attr,delta] of [['colLeft',-1],['colRight',1]])$$('[data-'+attr.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+']').forEach(e=>e.onclick=()=>{const i=+e.dataset[attr],j=i+delta;[s.columns[i],s.columns[j]]=[s.columns[j],s.columns[i]];s.rows.forEach(r=>[r.values[i],r.values[j]]=[r.values[j],r.values[i]]);markDirty();renderSize()});
 for(const [attr,delta] of [['rowUp',-1],['rowDown',1]])$$('[data-'+attr.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+']').forEach(e=>e.onclick=()=>{const i=+e.dataset[attr],j=i+delta;[s.rows[i],s.rows[j]]=[s.rows[j],s.rows[i]];markDirty();renderSize()});
 $$('[data-del-col]').forEach(e=>e.onclick=()=>{const i=+e.dataset.delCol;if(!confirm('Usunąć rozmiar „'+s.columns[i]+'” wraz z jego pomiarami?'))return;s.columns.splice(i,1);s.rows.forEach(r=>r.values.splice(i,1));markDirty();renderSize()});
 $$('[data-del-row]').forEach(e=>e.onclick=()=>{if(confirm('Usunąć pomiar i wszystkie jego wartości?')){s.rows.splice(+e.dataset.delRow,1);markDirty();renderSize()}});
 $('#addColumn').onclick=()=>{s.columns.push('Nowy '+(s.columns.length+1));s.rows.forEach(r=>r.values.push(''));markDirty();renderSize()};$('#addRow').onclick=()=>{s.rows.push({name:'Pomiar '+(s.rows.length+1),values:s.columns.map(()=>'')});markDirty();renderSize()};
 ['unit','tolerance','instructions'].forEach(id=>$('#'+id).oninput=e=>{s[id]=e.target.value;markDirty()});
 $('#saveTemplate').onclick=guard(async()=>{const name=prompt('Nazwa nowego szablonu tabeli:');if(!name?.trim())return;const c=clone(state.catalog);c.templates.push({id:crypto.randomUUID(),name:name.trim(),size:clone(s)});const r=await api('catalog',{catalog:c});state.catalog=r.catalog;toast('Szablon zapisany.');renderSize()});
}
function renderGallery(kind){
 const list=product.galleries[kind],limit=kind==='lifestyle'?5:18,root=$('#'+kind+'Gallery');$('#'+kind+'Count').textContent=list.length+'/'+limit;
 root.innerHTML=`<div class="gallery-list">${list.map((p,i)=>`<article class="gallery-item" draggable="true" data-index="${i}">${kind==='realizacje'?`<div class="gallery-order"><span>Pozycja na stronie</span><b aria-label="Pozycja ${i+1}">${String(i+1).padStart(2,'0')}</b></div>`:''}<img loading="lazy" src="${window.DW_BASE}/asset/${esc(p.src)}" alt="${esc(p.alt||p.title)}" style="object-position:${esc(p.position||'50% 50%')}"><label>Podpis zdjęcia<input data-title="${i}" maxlength="120" value="${esc(p.title)}"></label><label>Podtytuł (opcjonalnie)<input data-subtitle="${i}" maxlength="180" value="${esc(p.subtitle)}"></label><label>Tekst alternatywny<input data-alt="${i}" maxlength="250" value="${esc(p.alt)}"></label>${kind==='lifestyle'?`<label>Kadr zdjęcia<select data-position="${i}">${[['50% 50%','Środek'],['50% 20%','Wyżej'],['50% 80%','Niżej'],['20% 50%','W lewo'],['80% 50%','W prawo']].map(([value,name])=>`<option value="${value}" ${p.position===value?'selected':''}>${name}</option>`).join('')}</select></label>`:''}<div class="row-actions"><button data-up="${i}" ${i===0?'disabled':''} aria-label="Przesuń zdjęcie w górę">↑</button><button data-down="${i}" ${i===list.length-1?'disabled':''} aria-label="Przesuń zdjęcie w dół">↓</button><button data-replace="${i}">Podmień</button><button class="remove" data-remove="${i}">Usuń</button></div></article>`).join('')}</div>${!list.length?'<div class="empty">Dodaj pierwsze zdjęcie.</div>':''}${list.length>=limit?`<p class="notice">Osiągnięto limit ${limit} zdjęć ${kind}. Usuń lub zastąp zdjęcie.</p>`:''}<div class="gallery-buttons"><button class="small" data-upload ${list.length>=limit?'disabled':''}>＋ Wgraj zdjęcia</button><button class="small" data-library ${list.length>=limit?'disabled':''}>Wybierz z biblioteki</button></div>`;
 for(const key of ['title','subtitle','alt','position'])$$('[data-'+key+']',root).forEach(e=>e.oninput=()=>{list[+e.dataset[key]][key]=e.value;markDirty()});
 function move(i,j){[list[i],list[j]]=[list[j],list[i]];markDirty();renderGallery(kind)}
 $$('[data-up]',root).forEach(e=>e.onclick=()=>move(+e.dataset.up,+e.dataset.up-1));$$('[data-down]',root).forEach(e=>e.onclick=()=>move(+e.dataset.down,+e.dataset.down+1));
 $$('[data-remove]',root).forEach(e=>e.onclick=()=>{list.splice(+e.dataset.remove,1);markDirty();renderGallery(kind)});
 $$('[data-replace]',root).forEach(e=>e.onclick=guard(()=>pickMedia(1,items=>{list[+e.dataset.replace].src=items[0].src;markDirty();renderGallery(kind)})));
 const append=items=>{items.forEach(x=>list.push({src:x.src,title:'',subtitle:'',alt:'',position:'50% 50%'}));markDirty();renderGallery(kind)};
 $('[data-library]',root).onclick=guard(()=>pickMedia(limit-list.length,append));$('[data-upload]',root).onclick=()=>chooseUpload(limit-list.length,append);
 let dragged;$$('.gallery-item',root).forEach(e=>{e.ondragstart=ev=>{if(['INPUT','SELECT','BUTTON'].includes(ev.target.tagName)){ev.preventDefault();return}dragged=+e.dataset.index};e.ondragover=ev=>ev.preventDefault();e.ondrop=ev=>{ev.preventDefault();const to=+e.dataset.index;if(dragged!==undefined&&dragged!==to){const item=list.splice(dragged,1)[0];list.splice(to,0,item);markDirty();renderGallery(kind)}}});
}
async function save(){if(!dirty)return product;const button=$('#save');if(button)button.disabled=true;try{const r=await api('save',{product});product=r.product;dirty=false;const i=state.products.findIndex(p=>p.id===product.id);state.products[i]=clone(product);const y=window.scrollY;renderEditor();window.scrollTo(0,y);toast('Szkic zapisany. Strona lokalna pozostaje bez zmian.');return product}finally{if(button)button.disabled=false}}
async function preview(){await save();const r=await api('preview',{id:product.id});showModal('Podgląd • '+product.name,`<div class="toolbar"><select id="previewWidth" aria-label="Szerokość podglądu"><option value="100%">Dostępna szerokość</option><option value="390px">Telefon · 390 px</option><option value="768px">Tablet · 768 px</option><option value="1280px">Komputer · 1280 px</option></select><a class="small" href="${esc(r.url)}" target="_blank" rel="noopener">Otwórz osobno ↗</a></div><div class="preview-wrap"><iframe title="Podgląd produktu" src="${esc(r.url)}"></iframe></div>`);$('#previewWidth').onchange=e=>$('.preview-wrap iframe').style.width=e.target.value}
async function publication(){
 await save();await reload();
 const current=state.products.find(p=>p.id===product.id),warnings=current.warnings||[],errors=current.errors||[];
 const check=state.folder_mode?await api('publication-check?id='+encodeURIComponent(product.id)):null;
 const drift=check?.external_changed;
 const syncMessage=drift?`<div class="notice" role="alert"><b>Wykryto zmiany poza panelem.</b><p>Program zastosuje Twój szkic na AKTUALNYM pliku HTML. Pozostałe elementy bieżącego szablonu będą punktem wyjścia, ale edytowane pola produktu zostaną zastąpione wartościami ze szkicu.</p>${check.current_differences.length?`<p><b>Pola różniące się od szkicu (sprawdź przed potwierdzeniem):</b> ${check.current_differences.map(esc).join(', ')}.</p>`:''}<p>Przed zapisem powstanie kopia bezpieczeństwa. Jeżeli plik zmieni się ponownie po wyświetleniu tego raportu, zapis zostanie zatrzymany do ponownej kontroli.</p></div>`:'<p class="hint">Plik produktu jest zgodny ze szkicem w chwili kontroli.</p>';
 const clubMessage=check?`<div class="notice"><b>Kontrola relacji klubów</b>${check.club_notices.length?check.club_notices.map(m=>`<p>• ${esc(m)}</p>`).join(''):'<p>Nie wykryto konfliktów w oznaczonych zdjęciach tej karty.</p>'}${check.unassigned_count?`<p>Uwaga: ${check.unassigned_count} fotografii nie ma przypisanego klubu; nie można zweryfikować ich relacji.</p>`:''}<p>Informacje dotyczą układu galerii, nie zmieniają istniejących reguł doboru zdjęć. Silnik karuzeli nadal musi przestrzegać wykluczeń klubowych.</p></div>`:'';
 showModal('Zapisz zmiany w folderze strony',`<p>Produkt: <b>${esc(product.name)}</b></p><p>Adres: <code>${esc(product.url)}</code></p><p class="hint">Przed zmianami program zachowa kopię zastępowanych plików.</p>${syncMessage}${clubMessage}<div class="notice">Zakres: karta produktu, nawigacja i listing kategorii. Strony bez faktycznych zmian nie będą przepisywane.</div>${errors.length?`<div class="notice error"><b>Uzupełnij dane przed zastosowaniem:</b>${errors.map(e=>`<p>• ${esc(e)}</p>`).join('')}</div>`:''}${warnings.length?`<div class="notice"><b>Do sprawdzenia:</b>${warnings.map(e=>`<p>• ${esc(e)}</p>`).join('')}</div>`:''}${drift?'<label class="notice"><input id="syncConfirm" type="checkbox"> Rozumiem różnice i zatwierdzam nałożenie szkicu na aktualną kartę strony.</label>':''}<div class="modal-footer"><button id="cancelPublish">Wróć do edycji</button><button id="confirmPublish" class="primary" ${errors.length||drift?'disabled':''}>Zapisz do folderu strony</button></div><div id="publishProgress"></div>`);
 $('#cancelPublish').onclick=()=>modal.close();
 if(drift){$('#syncConfirm').onchange=()=>{$('#confirmPublish').disabled=errors.length||!$('#syncConfirm').checked;};}
 const key=crypto.randomUUID();
 $('#confirmPublish').onclick=guard(async()=>{
  const btn=$('#confirmPublish');btn.disabled=true;
  $('#publishProgress').innerHTML='<p class="hint">Przygotowywanie aktualizacji i kopii bezpieczeństwa…</p>';
  try{
   const r=await api('publish',{id:product.id,revision:product.revision,key,
      ack_external:!!drift,expected_live_hash:check?.current_hash});
   await reload();product=clone(state.products.find(p=>p.id===product.id));renderEditor();
   showModal('Zmiany zastosowane',`<p>Pliki zostały zaktualizowane.${r.external_sync?' Szkic zsynchronizowano z aktualną kartą strony.':''}</p><p><a class="primary" style="display:inline-block;padding:12px;border-radius:6px" href="${esc(r.url)}" target="_blank" rel="noopener">Otwórz produkt na stronie ↗</a></p><p class="hint">Wydanie: ${esc(r.release)}. Kopię sprzed zmiany znajdziesz w historii.</p>`);
  }catch(e){btn.disabled=false;$('#publishProgress').innerHTML=`<p class="notice error">${esc(e.message)}</p><p class="hint">Jeżeli plik zmienił się ponownie, zamknij to okno i otwórz raport synchronizacji jeszcze raz.</p>`;throw e;}
 });
}
async function pickMedia(max,callback){media=await api('media');let selected=new Set();showModal('Wybierz zdjęcia z biblioteki',`<div class="toolbar"><input id="mediaSearch" placeholder="Szukaj po nazwie…"><button id="uploadFromPicker">Wgraj nowe</button></div><p class="hint">Dostępne miejsca: ${max}. Zaznacz zdjęcia, następnie dodaj je do produktu.</p><div id="mediaResults" class="media-grid"></div><div class="modal-footer"><span id="selectedCount" class="hint">Wybrano: 0/${max}</span><button id="applyMedia" class="primary" disabled>Dodaj wybrane</button></div>`);function render(){const q=$('#mediaSearch').value.toLocaleLowerCase('pl');$('#mediaResults').innerHTML=media.filter(m=>m.name.toLocaleLowerCase('pl').includes(q)).map(m=>mediaCard(m,true,selected.has(m.id))).join('');$$('[data-media]').forEach(e=>e.onclick=()=>{const id=e.dataset.media;if(selected.has(id))selected.delete(id);else if(selected.size<max)selected.add(id);else return toast('Wybierz maksymalnie '+max+' zdjęć.',true);render();$('#selectedCount').textContent=`Wybrano: ${selected.size}/${max}`;$('#applyMedia').disabled=!selected.size})}$('#mediaSearch').oninput=render;$('#applyMedia').onclick=()=>{callback([...selected].map(id=>media.find(m=>m.id===id)));modal.close()};$('#uploadFromPicker').onclick=()=>chooseUpload(max,callback);render()}
function mediaCard(m,pick=false,selected=false){return `<article class="media-card ${pick?'pick':''} ${selected?'selected':''}" ${pick?`data-media="${m.id}" tabindex="0" role="button"`:''}><img loading="lazy" src="${window.DW_BASE}/asset/${esc(m.src)}" alt="${esc(m.name)}"><strong>${esc(m.name)}</strong><small>${m.width} × ${m.height} px · ${(m.bytes/1024/1024).toFixed(2)} MB</small><small>${m.usage?.length?'Użycie: '+esc(m.usage.join(', ')):'Brak przypisania w szkicach'}</small></article>`}
function chooseUpload(max,callback,icon=false){const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.multiple=max>1;input.onchange=()=>uploadDialog([...input.files],max,callback,icon);input.click()}
function uploadDialog(files,max,callback,icon){if(!files.length)return;showModal('Wgraj zdjęcia',`<p class="hint">Wybierz maksymalnie ${max} plików. Obsługiwane: JPEG, PNG i WebP. Limit: ${icon?2:20} MB; maksymalnie 40 megapikseli.</p>${files.map((f,i)=>`<label class="check"><input type="checkbox" data-file="${i}" ${i<max?'checked':''}>${esc(f.name)} · ${(f.size/1024/1024).toFixed(2)} MB</label>`).join('')}<div id="uploadStatus"></div><div class="progress"><div id="uploadProgress"></div></div><div class="modal-footer"><button id="abortUpload">Anuluj</button><button id="startUpload" class="primary">Wgraj wybrane</button></div>`);$('#abortUpload').onclick=()=>{uploadRequest?.abort();modal.close()};$('#startUpload').onclick=guard(async()=>{const indexes=$$('[data-file]:checked').map(e=>+e.dataset.file);if(!indexes.length||indexes.length>max)throw new Error('Wybierz od 1 do '+max+' plików.');const results=[];$('#startUpload').disabled=true;try{for(const [n,i] of indexes.entries()){const file=files[i];$('#uploadStatus').textContent=`${n+1}/${indexes.length}: ${file.name}`;if(file.size>(icon?2:20)*1024*1024)throw new Error(file.name+': przekroczono limit rozmiaru.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const item=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();uploadRequest=xhr;xhr.open('POST',window.DW_BASE+'/api/upload');xhr.setRequestHeader('Content-Type','application/json');xhr.setRequestHeader('X-DW-Token',window.DW_TOKEN);xhr.upload.onprogress=e=>{if(e.lengthComputable)$('#uploadProgress').style.width=Math.round(e.loaded/e.total*100)+'%'};xhr.onload=()=>{uploadRequest=null;const r=JSON.parse(xhr.responseText);if(xhr.status>=400)reject(new Error(r.error));else resolve(r)};xhr.onerror=()=>reject(new Error('Błąd połączenia. Możesz ponowić upload.'));xhr.onabort=()=>reject(new Error('Upload anulowany.'));xhr.send(JSON.stringify({name:file.name,data,icon}))});results.push(item)}callback(results);modal.close();toast('Zdjęcia wgrane i przetworzone.')}catch(e){if(modal.open){$('#uploadStatus').textContent=e.message+' Wgrane wcześniej pliki pozostały w bibliotece.';$('#startUpload').disabled=false}throw e}})}
async function renderLibrary(){media=await api('media');content.innerHTML=`<div class="intro"><p>Wspólne zdjęcia dla wszystkich produktów.<br>Usunięcie zdjęcia z galerii usuwa przypisanie, a plik pozostaje bezpieczny w bibliotece.</p><button id="libraryUpload" class="primary">＋ Wgraj zdjęcia</button></div><div class="toolbar"><input id="librarySearch" placeholder="Szukaj zdjęcia…" aria-label="Szukaj zdjęcia"><select id="usageFilter" aria-label="Filtr użycia"><option value="">Wszystkie pliki</option><option value="unused">Bez przypisania w szkicach</option></select></div><div id="libraryGrid" class="media-grid"></div>`;function render(){const q=$('#librarySearch').value.toLowerCase();$('#libraryGrid').innerHTML=media.filter(m=>m.name.toLowerCase().includes(q)&&(!$('#usageFilter').value||!m.usage.length)).map(m=>mediaCard(m)).join('')}$('#librarySearch').oninput=render;$('#usageFilter').onchange=render;$('#libraryUpload').onclick=()=>chooseUpload(50,()=>guard(renderLibrary)());render()}
function renderCatalog(kind){const c=clone(state.catalog);const titles={methods:'Metody znakowania',categories:'Kategorie',tables:'Szablony tabel'};const hint={methods:'Dodawaj metody wraz z opisem i ikoną. Istniejące produkty zachowują zapisane wersje metod.',categories:'Kategorie porządkują ofertę. Adres może zawierać kotwicę, np. fightwear.html#sportswear.',tables:'Tabele zapisane z edytora produktu można wykorzystać ponownie. Każdy produkt otrzymuje własną kopię.'};content.innerHTML=`<div class="intro"><p>${hint[kind]}</p>${kind!=='tables'?'<button id="addCatalog" class="primary">＋ Dodaj</button>':''}</div><div id="catalogItems"></div>${kind!=='tables'?'<button id="saveCatalog" class="primary">Zapisz słownik</button>':''}`;
 const list=kind==='methods'?c.methods:kind==='categories'?c.categories:c.templates;
 function render(){if(kind==='tables'){$('#catalogItems').innerHTML=list.length?list.map(t=>`<div class="catalog-card"><h3>${esc(t.name)}</h3><p class="hint">Rozmiary: ${t.size.columns.map(esc).join(', ')} · Pomiary: ${t.size.rows.map(r=>esc(r.name)).join(', ')}</p></div>`).join(''):'<div class="empty">Utwórz tabelę w produkcie i wybierz „Zapisz jako szablon”.</div>';return}
 $('#catalogItems').innerHTML=list.map((item,i)=>`<div class="catalog-card" data-catalog-index="${i}"><div class="fields"><label>Nazwa<input data-key="name" value="${esc(item.name)}"></label>${kind==='methods'?`<label>Krótka nazwa do parametrów<input data-key="short" value="${esc(item.short)}"></label><label class="full">Opis<textarea data-key="description">${esc(item.description)}</textarea></label>`:''}<label>Adres ${kind==='methods'?'procesu produkcji':'kategorii'}<input data-key="url" value="${esc(item.url)}"></label>${kind==='methods'?`<label>Tekst alternatywny ikony<input data-key="alt" value="${esc(item.alt)}"></label><div>${item.icon?`<img class="method-icon" style="float:none" src="${window.DW_BASE}/asset/${esc(item.icon)}" alt="">`:''}<button data-icon-library class="small">Wybierz ikonę</button> <button data-icon-upload class="small">Wgraj ikonę</button></div>`:''}<label class="check"><input type="checkbox" data-key="active" ${item.active?'checked':''}>Aktywna ${kind==='methods'?'metoda':'kategoria'}</label></div><div class="row-actions"><button data-catalog-up ${i===0?'disabled':''}>↑</button><button data-catalog-down ${i===list.length-1?'disabled':''}>↓</button></div></div>`).join('');
 $$('[data-catalog-index]').forEach(row=>{const i=+row.dataset.catalogIndex,item=list[i];$$('[data-key]',row).forEach(e=>e.oninput=()=>{item[e.dataset.key]=e.type==='checkbox'?e.checked:e.value;dirty=true});$('[data-catalog-up]',row).onclick=()=>{[list[i-1],list[i]]=[list[i],list[i-1]];dirty=true;render()};$('[data-catalog-down]',row).onclick=()=>{[list[i+1],list[i]]=[list[i],list[i+1]];dirty=true;render()};if(kind==='methods'){const cb=items=>{item.icon=items[0].src;dirty=true;render()};$('[data-icon-library]',row).onclick=guard(()=>pickMedia(1,cb));$('[data-icon-upload]',row).onclick=()=>chooseUpload(1,cb,true)}})}
 if(kind!=='tables'){$('#addCatalog').onclick=()=>{list.push({id:crypto.randomUUID(),name:'',short:'',description:'',url:kind==='methods'?'produkcja.html':'',icon:'',alt:'',active:true});dirty=true;render()};$('#saveCatalog').onclick=guard(async()=>{const r=await api('catalog',{catalog:c});state.catalog=r.catalog;dirty=false;toast('Słownik zapisany. Istniejące publikacje pozostają bez zmian.');renderCatalog(kind)})}render()}
async function showHistory(){const h=await api('history?id='+product.id);showModal('Historia produktu',`<p class="hint">Przywrócenie tworzy nowy szkic. Nie zmienia strony lokalnej.</p>${h.versions.map(v=>`<div class="list-row"><div><b>Wersja ${v.revision}</b><small>${new Date(v.at).toLocaleString('pl-PL')}</small></div><button data-restore="${v.revision}">Przywróć do szkicu</button></div>`).join('')}${product.published_revision?'<div class="modal-footer"><button id="unpublish" class="danger">Wycofaj produkt ze strony lokalnej</button></div>':''}`);$$('[data-restore]').forEach(e=>e.onclick=guard(async()=>{if(!confirm('Przywrócić tę wersję jako nowy szkic?'))return;const r=await api('restore',{id:product.id,revision:product.revision,target:+e.dataset.restore});await reload();product=r.product;dirty=false;renderEditor();modal.close();toast('Przywrócono dane do nowego szkicu.')}));if($('#unpublish'))$('#unpublish').onclick=guard(async()=>{if(!confirm('Wycofać produkt i odnośniki z lokalnego wydania?'))return;$('#unpublish').disabled=true;await api('unpublish',{id:product.id,revision:product.revision,key:crypto.randomUUID()});await reload();openEditor(product.id);modal.close();toast('Produkt wycofany ze strony lokalnej.')})}
async function historyPage(){const h=await api('history');content.innerHTML=`<p class="hint">Możesz cofnąć ostatnią publikację do plików sprzed jej wykonania. Operacja sprawdza, czy pliki nie zostały później zmienione poza panelem. Szkice pozostają zachowane.</p><div class="section">${h.releases.length?h.releases.map(r=>`<div class="list-row"><div><b>${esc(r.id)}</b><small>${new Date(r.at).toLocaleString('pl-PL')}${h.current===r.id?' · AKTUALNE WYDANIE':''}</small></div><button data-rollback="${r.id}" ${h.current!==r.id?'disabled':''}>Cofnij publikację</button></div>`).join(''):'<div class="empty">Brak publikacji panelu. Wyświetlane są aktualne pliki folderu strony.</div>'}</div>`;$$('[data-rollback]').forEach(e=>e.onclick=guard(async()=>{if(!confirm('Cofnąć ostatnią publikację w folderze strony?'))return;e.disabled=true;try{await api('rollback',{release:e.dataset.rollback});toast('Przywrócono kompletne wydanie.');await historyPage()}catch(ex){e.disabled=false;throw ex}}))}
function renderBackup(){content.innerHTML=`<div class="section"><h2>Kopia całej pracowni</h2><p class="hint">Archiwum zawiera dane panelu oraz aktualne pliki strony w katalogu website. Samo tworzenie kopii nie zmienia strony.</p><button id="makeBackup" class="primary">Utwórz kopię zapasową</button><div id="backupResult"></div></div><div class="section"><h3>Miejsce zapisu</h3><p><code>${esc(state.storage)}</code></p><p class="hint">Kopię ZIP możesz dodatkowo przechować na Google Drive lub drugim dysku. Instrukcja odtworzenia jest w pliku INSTRUKCJA.md obok programu.</p></div>`;$('#makeBackup').onclick=guard(async()=>{const b=$('#makeBackup');b.disabled=true;$('#backupResult').innerHTML='<p class="hint">Tworzenie i sprawdzanie archiwum. To może potrwać kilka minut…</p>';try{const r=await api('backup',{});$('#backupResult').innerHTML=`<p class="notice">Kopia utworzona i sprawdzona: <b>${esc(r.name)}</b><br>${(r.bytes/1024/1024).toFixed(1)} MB · folder data/backups</p>`}finally{b.disabled=false}})}
guard(async()=>{await reload();renderProducts()})();

function showSessionLogin(){
 if(document.getElementById('sessionNotice'))return;
 const notice=document.createElement('div');notice.id='sessionNotice';notice.className='session-notice';
 const text=document.createElement('span');text.textContent='Sesja wygasła. Zaloguj się ponownie, a potem wróć do edycji. ';
 const link=document.createElement('a');link.href=window.DW_BASE+'/login';link.target='_blank';link.rel='noopener';link.textContent='Otwórz logowanie ↗';
 notice.append(text,link);document.body.append(notice);
}
window.addEventListener('focus',async()=>{const n=document.getElementById('sessionNotice');if(n){try{const r=await fetch(window.DW_BASE+'/api/auth');const s=await r.json();if(s.authenticated)n.remove()}catch(e){}}});
$('#logout').onclick=guard(async()=>{if(!canLeave())return;await api('logout',{});dirty=false;location.replace(window.DW_BASE+'/login')});
$('#changePassword').onclick=()=>{
 showModal('Zmień hasło',`<form id="passwordForm" class="password-form"><label>Aktualne hasło<input name="current" type="password" autocomplete="current-password" required maxlength="128"></label><label>Nowe hasło<input name="next" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><label>Powtórz nowe hasło<input name="confirmation" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><p class="hint">Minimum 12 znaków. Zmiana hasła wyloguje pozostałe sesje.</p><div id="passwordError" role="alert"></div><button type="submit" class="primary">Zmień hasło</button></form>`);
 $('#passwordForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=$('button[type=submit]',form);button.disabled=true;try{const data=new FormData(form);await api('password',{current_password:data.get('current'),password:data.get('next'),confirmation:data.get('confirmation')});form.reset();modal.close();toast('Hasło zmienione. Pozostałe sesje zostały wylogowane.')}catch(ex){$('#passwordError').textContent=ex.message;button.disabled=false}};
};
